# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/grpc/protos/service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'common/grpc/protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n common/grpc/protos/service.proto\x12\tgame.grpc\"\xb0\x01\n\nRpcRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.game.grpc.RpcRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x0bRpcResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x32\x85\x01\n\x0bGameService\x12\x35\n\x04\x43\x61ll\x12\x15.game.grpc.RpcRequest\x1a\x16.game.grpc.RpcResponse\x12?\n\nStreamCall\x12\x15.game.grpc.RpcRequest\x1a\x16.game.grpc.RpcResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.grpc.protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPCREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_RPCREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RPCREQUEST']._serialized_start=48
  _globals['_RPCREQUEST']._serialized_end=224
  _globals['_RPCREQUEST_METADATAENTRY']._serialized_start=177
  _globals['_RPCREQUEST_METADATAENTRY']._serialized_end=224
  _globals['_RPCRESPONSE']._serialized_start=226
  _globals['_RPCRESPONSE']._serialized_end=287
  _globals['_GAMESERVICE']._serialized_start=290
  _globals['_GAMESERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
