# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import service_pb2 as service__pb2


class GameServiceStub(object):
    """定义通用服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/game.grpc.GameService/Call',
                request_serializer=service__pb2.RpcRequest.SerializeToString,
                response_deserializer=service__pb2.RpcResponse.FromString,
                )
        self.StreamCall = channel.stream_stream(
                '/game.grpc.GameService/StreamCall',
                request_serializer=service__pb2.RpcRequest.SerializeToString,
                response_deserializer=service__pb2.RpcResponse.FromString,
                )


class GameServiceServicer(object):
    """定义通用服务
    """

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCall(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=service__pb2.RpcRequest.FromString,
                    response_serializer=service__pb2.RpcResponse.SerializeToString,
            ),
            'StreamCall': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCall,
                    request_deserializer=service__pb2.RpcRequest.FromString,
                    response_serializer=service__pb2.RpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.grpc.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """定义通用服务
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.grpc.GameService/Call',
            service__pb2.RpcRequest.SerializeToString,
            service__pb2.RpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/game.grpc.GameService/StreamCall',
            service__pb2.RpcRequest.SerializeToString,
            service__pb2.RpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
