# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.grpc.protos import service_pb2 as common_dot_grpc_dot_protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in common/grpc/protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """定义通用服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/game.grpc.GameService/Call',
                request_serializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.SerializeToString,
                response_deserializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.FromString,
                _registered_method=True)
        self.StreamCall = channel.stream_stream(
                '/game.grpc.GameService/StreamCall',
                request_serializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.SerializeToString,
                response_deserializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """定义通用服务
    """

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCall(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.FromString,
                    response_serializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.SerializeToString,
            ),
            'StreamCall': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCall,
                    request_deserializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.FromString,
                    response_serializer=common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.grpc.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game.grpc.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """定义通用服务
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.grpc.GameService/Call',
            common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.SerializeToString,
            common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/game.grpc.GameService/StreamCall',
            common_dot_grpc_dot_protos_dot_service__pb2.RpcRequest.SerializeToString,
            common_dot_grpc_dot_protos_dot_service__pb2.RpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
