# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/base_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/protocol/base_message.proto\x12\rgame.protocol\"L\n\x06Header\x12\x0e\n\x06length\x18\x01 \x01(\r\x12\x0e\n\x06msg_id\x18\x02 \x01(\r\x12\x10\n\x08sequence\x18\x03 \x01(\r\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\r\"k\n\x0b\x42\x61seRequest\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.game.protocol.Header\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"e\n\x0c\x42\x61seResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.game.protocol.Header\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.protocol.base_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEADER']._serialized_start=53
  _globals['_HEADER']._serialized_end=129
  _globals['_BASEREQUEST']._serialized_start=131
  _globals['_BASEREQUEST']._serialized_end=238
  _globals['_BASERESPONSE']._serialized_start=240
  _globals['_BASERESPONSE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
